    function generateQuote() {
      var quotes = [
        "Let’s try try try MAKAFUSHIGI",
        "I BUY SAUSAGE!",
        "darlin' darlin' freeze!!",
        "Timotei~",
        "Which end of a chocolate cornet do you eat first?",
        "ざわ･･ざわ･･",
        "みWiki",
        "Can anyone here read moonrunes?",
        "I will dance and I'll defeat them through the light and the dark",
        "journey to lavender waters",
        "You drank up my bodily fluid with such vigour……",
        "Puru puru pururin pururin",
        "The real me is still asleep, so that’s why my life is such garbage.",
        "Mirai wa bokura no te no naka",
        "Just according to keikaku.",
        "Kagami-sama",
        "Raspberry heaven",
        "Honey sweet tea time",
        "You are truly slothful!",
        "My brain trembles!",
        "Is mayonnaise an instrument?",
        "The end of Snake Way",
        "That's 65% more bullet per bullet!",
        "Don’t worry about quality. I’ve got quantity!",
        "Tahmano",
        "Deep wide bell, wonder",
        "Kimochi warui",
        "Get away from the Internet! I'm cutting it down, right now.",
        "Eat your heart out Zuckerberg.",
        "Foolish guac bowl merchant",
        "When it roars, it sounds like a telephone.",
        "Where's my co-co-cola?",
        "Nipah~",
        "Soul Brothers, assemble!",
        "Welcome to the Project!",
        "Nihon Hikikomori Kyoukai",
        "Neko Mimi Mode!",
        "I'm drinking Rolling Rock on the Roll N Rocker!",
        "Cool clock, Ahmed.",
        "one delta ten tango",
        "The Grinch in a mask holding a gun.",
        "Museum of Kek",
        "Listen kid I don't have much time, I have information that will indict Hillary Clin…",
        "Helvetica Standard",
        "*click* Noice",
        "Oh the camera’s on?",
        "Don’t be Rama Rama",
        "Consume the chalice",
        "It’s not too late to change your hikikomori ways!",
        "Dynamic Entry!",
        "The Witches' Tea Party",
        "I'm feelin' like a total barnacle head!",
        "The pioneers used to ride these babies for miles!",
        "Ravoli, ravoli, give me the formuoli!",
        "We had a teacher who was so strict, you weren't allowed to breathe in her lessons.",
        "I’ll take a nap until around 2:00 PM. So please stick around until five o'clock or so.",
        "At last! STIMULATION!",
        "People sleep well when they’re satisfied with their day, you see.",
        "All right...I talked with one person, I filled my quota for today!",
        "Switch Princess",
        "Happy! Lucky! Dochy!",
        "Go Go Girl Ichigo Love!",
        "EMT!",
        "Don't lose your way.",
        "kero kero",
        "My mom came into my room to bring me a plate of chicken nuggets and I literally screamed at her and hit the plate of chicken nuggets out of her hand.",
        "Uboa's trap",
        "Drink cactus juice",
        "Bludgeoning angel",
        "Delicious Fruit",
        "W32/Hoots-A",
        "Don’t Worry, He Knows",
        "Come on, drink this! You like vegetable juice, don’t you? I’ve decided that you must, right now!",
        "CUMON STEP IT UP!!!!!",
        "ERIITO SENSHI",
        "Never ending girls' talk",
        "Jun-chan, welcome back.",
        "Ken Ishiyama vs Junko Furuta",
        "It’s time to gamble and prove our respective worth.",
        "Oh, us adults are always in pain. That’s why we’re allowed to drink alcohol!",
        "Right now you’re on the threshold of an amazing adventure.",
        "Walpurgisnacht",
        "If it were up to me, I'd rather we be called 'residentially challenged'.",
        "I’ve completely wasted my entire life…!",
        "I first met her in a dream...or something.",
        "Make a contract with me and become a magical girl!",
        "Girls can't love girls. Girls can't love girls. Girls can't love girls!",
        "A net-pal isn't the same as a real friend.",
        "Just kill me now.",
        "Yeah. You're right. I'll kill myself.",
        "No human language can describe the disappointment I'm feeling right now.",
        "I could be out on Sixth Street right now!",
        "Pum-pumpkin",
        "You can see them if you're driving.",
        "Now, listen, Mustard Man, or whatever you call yourself.",
        "Sample Text",
        "Why don’t you enjoy a cup of calming jasmine tea?",
        "But why have we been turned into fruits?",
        "Go stand in the hallway, Sasazuka.",
        "I’m not having fun. I’m really not having fun!",
        "Take the six nuggets, and throw two of them away.",
        "New World Discovery Club",
        "Hole Digging Club",
        "Last tour on a Kettenkrad",
        "Marvelous Marno’s Master-Blaster",
        "Every time I brandish my cutting knife, the raccoon shows me its excitement.",
        "The ink flows down into a dark puddle.",
        "In the distance, a blue-green light flickers.",
        "The last remaining streetlight to have withstood the test of time.",
        "In the meantime, we can just look into each other's eyes~",
        "You have no chance to survive make your time.",
        "Oh no, he's hot!",
        "Felicitations, malefactors!",
        "Would anyone else like to enter the Fly of Despair?",
        "People Order Our Patties",
        "Every Villain Is Lemons",
        "How long has it been since we had a bath?",
        "Are pants people!?",
        "Even if the world does not forgive you, I will forgive you.",
        "Witch of Miracles",
        "Since my car has air conditioning, let’s talk in there.",
        "Let's get our gambling freak on!",
        "Played college ball, you know.",
        "Nanomachines, son!",
        "La chaleur me dérange, mais c'est le grinçement des bateaux qui m'a réveillée.",
        "Yamaku Academy",
        "The United States will buy the power of Kira for 500 billion dollars.",
        "YOUR DAUGHTER'S BODY IS SWARMING WITH MAGGOTS!! SERVES YOUUU RIGHT!!",
        "I don’t want to work!",
        "Once you've taken a man out for whiskey and ribs...then fought him...then fought the police with him...Well, you have forged a friendship thicker than any soup you can buy.",
        "Victor Echo 1 2",
        "Just like the simulations!",
        "100, 200, 300! You guys are gonna make me rich.",
        "517 to scanner control. 517 to scanner control.",
        "Clear bay 327. We are opening the magnetic field.",
        "OH DESIRE",
        "NYUHANPUSHA SUMASSHU",
        "Moshi Moshi, Jesus desu~",
        "Where there’s smoke, they pinch back.",
        "That maid is a killer robot from the future.",
        "Sea of Fragments",
        "らららコッペパン",
        "I did it! I had a totally natural conversation with somebody!",
        "Why do you think people stay up at night?",
        "This is what it feels like to sleep with someone?"
      ];
      var randomNumber = Math.floor(Math.random() * quotes.length);
      document.getElementById("quote").innerHTML = quotes[randomNumber];
    }
